# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

FROM debian:bookworm-slim

RUN apt-get update
RUN apt-get install -y make gcc gcc-aarch64-linux-gnu flex bison sparse libssl-dev bc git libelf-dev
